version: '3'

services:
  odoodb:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    networks:
      - odoonet

  odoo11:
    image: odoo:12.0
    ports:
      - 5000:8069
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./web_data:/var/lib/odoo
    depends_on:
      - odoodb
    environment:
      - HOST=odoodb
    networks:
      - odoonet

networks:
  odoonet: