version: '3'

services:
  odoodb:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    networks:
      - odoonet
    volumes:
      - db_data:/var/lib/postgresql/data
    stdin_open: true
    tty: true

  odoo11:
    image: odoo:11.0
    ports:
      - 5000:8069
    volumes:
      - ./odoo_addons:/mnt/extra-addons
      - ./odoo_config:/etc/odoo
      - ./odoo_web_data:/var/lib/odoo
    depends_on:
      - odoodb
    stdin_open: true
    tty: true
    environment:
      - HOST=odoodb
    networks:
      - odoonet

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8090:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=kevin@katana.do
      - PGADMIN_DEFAULT_PASSWORD=admin
    stdin_open: true
    tty: true
    networks:
      - odoonet

networks:
  odoonet:

volumes:
  db_data: